### ISSUE TITLE
Memory allocation on GPU

### ISSUE THREAD

**Issue by AasherH** [octo-models/octo#109]
I am loading the octo-small model on my GPU (NVIDIA GeForce RTX 4090) and checking nvidia-smi shows that it uses about 20GB of memory storage, which seems high to me. Upon loading the octo-base model, it still takes up about 20GB of storage, which doesn't make much sense. Does anyone know how I can decrease the amount of memory allocated to loading the pretrained octo model, or do these numbers sound about right to everyone?

**Comment by ojh6404** [comment]
See https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html

**Comment by AasherH** [comment]
Exactly
