### ISSUE TITLE
about dataset_statistics

### ISSUE THREAD

**Issue by zhang-haojie** [octo-models/octo#113]
When I run `03_eval_finetuned.py`, in lines 78, `octomodel.dataset_statistics` as a dictionary will index `['action']`, `model.dataset_statistics["action"]`. But when I check `dataset_statistics.json` in checkpoints, `action` is an attribute of a specific dataset. Is there any error in the code here?
![image](https://github.com/octo-models/octo/assets/68622230/f43751fb-9826-409e-9846-5555069cf4ec)
![image](https://github.com/octo-models/octo/assets/68622230/25be631f-d4c5-4eda-ad82-dc4778d59dd9)

**Comment by dibyaghosh** [comment]
Great question! This is just a difference between the pre-trained model (which is trained on a mix of different datasets) and finetuned models (which is trained on a single dataset). 

For models trained on a mix of datasets (e.g. in pretraining), the `make_interleaved_dataset` returns the statistics for each dataset separately in a dict (so you must index  like model.dataset_statistics[dataset_name]['action']), but make_single_dataset (used in finetuning) directly returns the dataset statistics trained on a single dataset (so you access model.dataset_statistics['action'])

**Comment by zhang-haojie** [comment]
Thank you for your timely answer to my question. It is already a very good code design!
