### ISSUE TITLE
Possibly incorrect order of operations in normalization

### ISSUE THREAD

**Issue by seann999** [octo-models/octo#14]
I think it should be (x - mean) * std?

https://github.com/octo-models/octo/blob/37951e4e6d708fd76374f6e09e716763fe2673b1/octo/utils/gym_wrappers.py#L283-L285

**Comment by kpertsch** [comment]
Ah good catch! Fixed it in #15 .
This should only affect scenarios in which you pass proprio to the policy (which needs to get normalized), eg the ALOHA finetune example.
