### ISSUE TITLE
Running finetune script with text conditioning only

### ISSUE THREAD

**Issue by lyshuga** [octo-models/octo#17]
Hi,

In the finetune_config.py I have selected only text_conditioning, but there is a bug issue that occurs in the finetuning code:

  File "/home/users/m/octo/octo/data/dataset.py", line 98, in apply_trajectory_transforms
    getattr(goal_relabeling, goal_relabeling_strategy),
AttributeError: module 'octo.data.utils.goal_relabeling' has no attribute 'no_image_conditioning'

In file goal_relabeling indeed no function "no_image_conditioning", so I was wondering if you would release it?

Thank in advance.

**Comment by kvablack** [comment]
Apologies for the oversight, you can just set `goal_relabeling_strategy=None` and it will skip adding image goals. Fixed in #19.
