### ISSUE TITLE
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to allocate 98697216 bytes for new constant

### ISSUE THREAD

**Issue by devmonkeyx** [octo-models/octo#22]
When running the examples/03_eval_finetuned.py script on a GPU (A100 80G, cuda12.2), I encountered the following error:
`jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to allocate 98697216 bytes for new constant
`

Here are details:

> Traceback (most recent call last):
>   File "/home/houxuan/code/robot/octo/examples/03_eval_finetuned1.py", line 217, in <module>
>     app.run(main)
>   File "/home/houxuan/miniconda3/envs/octo/lib/python3.10/site-packages/absl/app.py", line 308, in run
>     _run_main(main, args)
>   File "/home/houxuan/miniconda3/envs/octo/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
>     sys.exit(main(argv))
>   File "/home/houxuan/code/robot/octo/examples/03_eval_finetuned1.py", line 193, in main
>     actions = policy_fn(
>   File "/home/houxuan/miniconda3/envs/octo/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 177, in reraise_with_filtered_traceback
>     return fun(*args, **kwargs)
>   File "/home/houxuan/miniconda3/envs/octo/lib/python3.10/site-packages/jax/_src/pjit.py", line 256, in cache_miss
>     outs, out_flat, out_tree, args_flat, jaxpr = _python_pjit_helper(
>   File "/home/houxuan/miniconda3/envs/octo/lib/python3.10/site-packages/jax/_src/pjit.py", line 167, in _python_pjit_helper
>     out_flat = pjit_p.bind(*args_flat, **params)
>   File "/home/houxuan/miniconda3/envs/octo/lib/python3.10/site-packages/jax/_src/core.py", line 2656, in bind
>     return self.bind_with_trace(top_trace, args, params)
>   File "/home/houxuan/miniconda3/envs/octo/lib/python3.10/site-packages/jax/_src/core.py", line 388, in bind_with_trace
>     out = trace.process_primitive(self, map(trace.full_raise, args), params)
>   File "/home/houxuan/miniconda3/envs/octo/lib/python3.10/site-packages/jax/_src/core.py", line 868, in process_primitive
>     return primitive.impl(*tracers, **params)
>   File "/home/houxuan/miniconda3/envs/octo/lib/python3.10/site-packages/jax/_src/pjit.py", line 1212, in _pjit_call_impl
>     return xc._xla.pjit(name, f, call_impl_cache_miss, [], [], donated_argnums,
>   File "/home/houxuan/miniconda3/envs/octo/lib/python3.10/site-packages/jax/_src/pjit.py", line 1196, in call_impl_cache_miss
>     out_flat, compiled = _pjit_call_impl_python(
>   File "/home/houxuan/miniconda3/envs/octo/lib/python3.10/site-packages/jax/_src/pjit.py", line 1152, in _pjit_call_impl_python
>     return compiled.unsafe_call(*args), compiled
>   File "/home/houxuan/miniconda3/envs/octo/lib/python3.10/site-packages/jax/_src/profiler.py", line 340, in wrapper
>     return func(*args, **kwargs)
>   File "/home/houxuan/miniconda3/envs/octo/lib/python3.10/site-packages/jax/_src/interpreters/pxla.py", line 1152, in __call__
>     results = self.xla_executable.execute_sharded(input_bufs)
> jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to allocate 98697216 bytes for new constant

Making the following modification in the code resolves the problem:
```python
    # jit model action prediction function for faster inference
    # policy_fn = jax.jit(model.sample_actions)
    policy_fn = model.sample_actions
```

any suggestion for how to make jax.jit transformation work?

**Comment by kvablack** [comment]
Sorry, that line should not even be in there. If you look at `model.sample_actions`, it's jitted already. Thanks for the catch!
