### ISSUE TITLE
Inconsistencies in model fine-tuning

### ISSUE THREAD

**Issue by andrearosasco** [octo-models/octo#38]
Hello, thanks for the amazing work!
I want to execute the script `examples/02_finetune_new_observation_action.py` obtain a fine tuned version of octo to test in the aloha gym environment. I started the training on an A100 but I'm noticing some differences with what it is written in the report:
- The script trains the model for **5k steps** instead of **50k steps**
- The fine-tuning process is currently taking **77GB** of VRAM while it should be able to run on **24GB**
- The current estimate to get to 5k steps is **80h** instead of **5h**

Also, I'm doing the finetuning on `octo-small` and the 24GB and 5h fine-tuning refers to `octo-base` so I was expecting it to take even less.

I was wondering whether fine-tuning on the aloha benchmark requires different hyperparameters which results in the inconsistencies or there is an error in the finetuning script. 

The only modifications I've done to the code are:
```python
flags.DEFINE_string(
    "pretrained_path", 'hf://rail-berkeley/octo-small', "Path to pre-trained Octo checkpoint directory."
)
flags.DEFINE_string("data_dir", '.', "Path to finetuning dataset, in RLDS format.")
flags.DEFINE_string("save_dir", './aloha_octo', "Directory for saving finetuning checkpoints.")
```
As all the values were previously set to `None`.

Do you have any idea what the issue might be?

Thanks in advance 🐙

**Comment by HM102** [comment]
did you find the problem with the memory. Mine is taking more the 70 GB for the base model
