### ISSUE TITLE
Can you provide finetuning ckpt

### ISSUE THREAD

**Issue by zwbx** [octo-models/octo#60]
Hi thanks your great work. I notice that you provide the finetune code, do you consider to directly provide the ckpt of finetuning example?

**Comment by kpertsch** [comment]
We don't provide checkpoints for the finetuned models since they are very specific to the setups they were finetuned in, so it would be very hard to reproduce these setups elsewhere. Best to collect a small dataset in your own setup and run the finetuning yourself!
