### ISSUE TITLE
UR wiping dataset

### ISSUE THREAD

**Issue by Nimingez** [octo-models/octo#89]
Can I replicate your wiping work with my UR5?
Could you please provide the UR5 wiping dataset? I couldn't find it in Open X-Embodiment.
![image](https://github.com/octo-models/octo/assets/104558844/f6865900-2e08-4331-863f-3a2035f4040e)

**Comment by kpertsch** [comment]
It's the "Berkeley Autolab UR5" dataset

https://docs.google.com/spreadsheets/d/1rPBD77tk60AEIGZrGSODwyyzs5FgCU9Uz3h-3_t2A9g/edit?usp=sharing

<img width="712" alt="image" src="https://github.com/octo-models/octo/assets/15955682/984bfb4f-5589-4dc0-8c30-f078eab07cc0">

**Comment by Nimingez** [comment]
The data consists of 4 robot manipulation tasks: simple pick-and-place of a stuffed animal between containers, sweeping a cloth, stacking cups, and a more difficult pick-and-place of a bottle that requires precise grasp and 6DOF rotation 。did not contain wiping发自我的 iPhone在 2024年5月10日，00:34，Karl Pertsch ***@***.***> 写道：﻿
It's the "Berkeley Autolab UR5" dataset
https://docs.google.com/spreadsheets/d/1rPBD77tk60AEIGZrGSODwyyzs5FgCU9Uz3h-3_t2A9g/edit?usp=sharing
image.png (view on web)

**Comment by kpertsch** [comment]
Sweeping a cloth == wiping 

-- sorry I may not be understanding your question correctly?

**Comment by Nimingez** [comment]
Thank you, I understand now
